version: "3"
services:
  web:
    build: server/
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    restart: on-failure

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nono
      - MYSQL_USER=yoann
      - MYSQL_PASSWORD=secret
